# Generated by Django 5.2.4 on 2025-07-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbeo', '0002_remove_costofliving_apartment_1_bedroom_in_city_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costofliving',
            name='apples_1kg',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='蘋果 (1公斤)'),
        ),
        migrations.AlterField(
            model_name='costofliving',
            name='banana_1kg',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='香蕉 (1公斤)'),
        ),
        migrations.AlterField(
            model_name='costofliving',
            name='oranges_1kg',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='橘子 (1公斤)'),
        ),
        migrations.AlterField(
            model_name='costofliving',
            name='tomato_1kg',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='番茄 (1公斤)'),
        ),
    ]
